Nemo/Added active_record validation. Added js validation. Added tests.
department-of-veterans-affairs/caseflow-feedback pull request #126
Opened 2017-03-15 18:52 UTC by nemodjuric

Fixes #122 

I added both active_record and front end validation. Error message -  kudos to @cmgiven 

![caseflow feedback 19](https://cloud.githubusercontent.com/assets/4960030/23965625/f35764a2-098e-11e7-813d-96cc1d747be3.png)

2017-03-15 21:20 UTC, shanear requested changes
Thanks for the quick turnaround on this!

Have some comments. Also this could use a functional test.

2017-03-15 21:20 UTC, shanear commented on app/assets/javascripts/feedback.js
> +    if (pii) {
This could be rewritten shorter like:
```
return pii && pii[pii.length-1];
```

2017-03-15 21:20 UTC, shanear commented on app/assets/javascripts/feedback.js
>    function validateQuestion(questionName, showError) {
This method is getting pretty unwieldy. Any way we can refactor?

2017-03-15 21:20 UTC, shanear commented on app/assets/javascripts/feedback.js
> +  // "/((?<![0-9])[0-9]{3}[- ]?[0-9]{2}[- ]?[0-9]{4}(?![0-9])S?|(?<![0-9])[0-9]{7,8}(?![0-9])C?)/"
this comment seems superfluous

2017-03-15 21:20 UTC, shanear commented on app/models/feedback.rb
> +                       format: { without: /((?<![0-9])[0-9]{3}[- ]?[0-9]{2}[- ]?[0-9]{4}
can we assign this beasty pattern to a constant like `PII_PATTERN`

2017-03-16 20:19 UTC, nemodjuric commented
Created #128 for functional tests.

2017-03-17 19:05 UTC, cmgiven commented
Can we update the regex to the following? This'll work in both JS and Ruby. Also note that it will only return a single match group.

Necessary because I learned that there's an additional format for SS and C numbers that the board uses on decisions. Probably won't come up given our current user base, but once we start shipping things to BVA, it might.

`((?:^|[^0-9]|SS )[0-9]{3}[- ]?[0-9]{2}[- ]?[0-9]{4}(?![0-9])S?|(?:^|[^0-9]|C )[0-9]{1,2} ?[0-9]{3} ?[0-9]{3}(?![0-9])C?)`

2017-03-21 15:25 UTC, shanear approved these changes

2017-03-21 15:25 UTC, merged