Anya/71 generate GitHub issue
department-of-veterans-affairs/caseflow-feedback pull request #96
Opened 2017-01-19 15:23 UTC by aroltsch

Automatically generate a Github issue when feedback is submitted

Note: we need to create a "support" user in Github and use this user's access_token to create issues.

connects #71

2017-01-19 20:51 UTC, shanear requested changes
This is awesome, just 2 comments

2017-01-19 20:51 UTC, shanear commented on app/services/github_service.rb
> +    body = GithubIssueRenderer.new(username: record.username,
maybe it'd be better to move this out to a place where we could test it

then the method would be: 
```
def create_issue(body)
end
```

Then we can do a test that the template is being filled out correctly

2017-01-19 20:51 UTC, shanear commented on app/models/feedback.rb
> +  after_create :create_github_issue
can we add a feature test for this?

2017-01-19 21:52 UTC, aroltsch commented on app/services/github_service.rb
> +    body = GithubIssueRenderer.new(username: record.username,
I am testing the template in github_issue_renderer_spec.rb. However, I think I understand what you mean :). @shanear

2017-01-19 21:52 UTC, aroltsch commented on app/models/feedback.rb
> +  after_create :create_github_issue
will do.

2017-01-23 15:52 UTC, shanear approved these changes
👍

2017-01-23 20:52 UTC, merged